config/routes.rb
      resources :attachments, :only => [:index, :new, :create]
      resources :forum_topics, :only => [:index, :new, :create]
      resources :lessons, :only => [:index, :new, :create]
      #resources :scheduled_courses, :only => [:index, :new,:create]
      resources :scheduled_courses, only: [:index]
    end

    resources :blogs do
      member do
        get 'delete'
      end

      resources :attachments, :only => [:index, :new, :create]
    end

    resources :certificate, only: [:index, :generate] do
      collection do
        post 'generate'
      end
    end
    resources :renewals, only: [:index, :create, :destroy]

    resources :workshops do
      member do
        get 'delete'
      end
    end

    resources :packages do
      member do
        get 'delete'
      end
      resources :attachments, :only => [:index, :new, :create]
    end

    resources :banner_images, only: [:index, :create, :destroy]
    resources :student_galleries, only: [:index, :create, :destroy]
    resources :contests, only: [:index, :create, :destroy, :new]
    resources :contest_descriptions, only: [:index, :create, :new, :edit]

    resources :settings

    resources :forum_topics do
      member do
        get 'delete'
      end
      resources :posts, :controller => 'forum_posts', :only => [:new, :create]
    end

    resources :lessons, :except => [:index, :new, :create] do
      member do
        get 'delete'
      end
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
      resources :assignments, :only => [:index, :new, :create]
    end

    resources :assignments, :except => [:index, :new, :create] do
      member do
        get 'delete'
      end
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
      resources :rearrangements
    end

    resources :rearrangements, :except => [:index, :new, :create] do
      member do
        get 'delete'
      end
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
    end

    resources :scheduled_assignments, :only => :show do
      resources :submissions, :controller => 'assignment_submissions', :only => :index
    end

    resources :assignment_submissions, :except => [:index, :new, :create] do
      member do
        get 'delete'
      end
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
      resources :critiques, :only => [:new, :create]
    end

    resources :scheduled_courses, :only => [:show] do
      resources :enrolments, :only => [:index, :new, :create]
    end

    resources :critiques, :only => [:edit, :update, :destroy] do
      member do
        get 'delete'
      end
    end

    resources :enrolments, :only => [:edit, :update, :destroy] do
      member do
        get 'delete'
      end
    end

    resources :forum_posts, :only => [:edit, :update, :destroy] do
      member do
        get 'delete'
      end
    end

    resources :exchange_rates, :except => :show do
      member do
        get 'delete'
      end
    end

    resources :partners do
      member do
        get 'delete'
      end
    end

    resources :gifts
  end

  namespace :instructor do
    resource :account, :controller => 'users', :only => [:edit, :update]
    resources :attachments do
      member do
        get 'delete'
      end
    end

    resources :lessons_comment, :only => [:delete] do
      member do
        get 'delete'
      end
    end
    resources :lessons, :only => :show
    resources :assignments, :only => :show
    resources :updates, :only => [:index]
    resources :mystudents, :only => [:index] do
      member do
        get 'courses'
      end
    end
    resources :courses, :only => :index do
      resources :scheduled_courses, :only => :index
    end
    resources :scheduled_courses, :only => [:show, :destroy] do
      member do
        get 'delete'
      end
      resources :enrolments, :only => [:index, :new, :create]
    end
    resources :forum_topics, :except => :destroy do
      resources :posts, :controller => 'forum_posts', :only => [:new, :create]
    end

    resources :submissions, :controller => 'assignments_submissions', :except => [:new, :create] do
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
      resources :critiques, :controller => 'assignment_critiques', :only => [:new, :create]
      #resource :sequence
    end
    resources :forum_posts, :only => [:edit, :update]
    get 'sequence/:id', :controller => "assignment_submissions", :action => 'sequence', as: :instructor_sequence

    get 'lessons/:lesson_id/attachments/new', :controller => "upload_video", :action => 'new', :as => 'lession'
    get 'lessons/:lesson_id/attachments', :controller => "upload_video", :action => 'new', :as => 'lession1'
    post 'lessons/:lesson_id/attachments', :controller => "upload_video", :action => 'create', :as => 'path_video'
    #
    get 'lessons/:lesson_id/upload', :controller => "upload_video", :action => 'upload', :as => 'inst_assignment'
    get 'lessons/:lesson_id', :controller => "upload_video", :action => 'upload', :as => 'inst_assignment1'
    post 'lessons/:lesson_id', :controller => "upload_video", :action => 'upload_video', :as => 'path_video_attach'
  end
  get 'courses/fulldownload', :controller => 'courses', :action => 'fulldownload'

  namespace :student do
    resource :account, :controller => 'users', :only => [:edit, :update]
    resources :attachments do
      member do
        get 'delete'
      end
      collection do
        post 'order'
      end
    end

    resources :courses, :controller => 'scheduled_courses' do
      resources :lessons, :controller => 'scheduled_lessons', :only => :show
      resources :reviews, only: [:new, :create, :destroy]
    end

    resources :assignments, :controller => 'scheduled_assignments' do
      resources :submissions, :controller => 'assignment_submissions', :only => [:new, :create]
    end

    resources :submissions, :controller => 'assignment_submissions', :except => [:new, :create] do
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
          get 'sequence'
        end
      end
      resources :critiques do
        resources :critiques, :only => [:new, :create]
      end
    end

    resources :forum_topics, :except => :destroy do
      resources :posts, :controller => 'forum_posts', :only => [:new, :create]
    end
    resources :updates, :only => [:index]
    resources :forum_posts, :only => [:edit, :update]

    get 'sequence/:id', :controller => "assignment_submissions", :action => 'sequence', as: :student_sequence

    get 'lessons/:lesson_id/assignments/:assignments_id/attachments/new', :controller => "upload_video", :action => 'new', :as => 'stdunt_post_video'
    get 'lessons/:lesson_id/assignments/:assignments_id/attachments', :controller => "upload_video", :action => 'new', :as => 'stdunt_post_video1'
    post 'lessons/:lesson_id/assignments/:assignments_id/attachments', :controller => "upload_video", :action => 'create', :as => 'post_video'
  end
  get 'attachments/:id/:style.:format', :controller => 'attachments', :action => 'download', as: :attachment_download

  get "paypal" => "purchase_notifications#paypal", :path => "purchase_notifications/paypal"

  post 'purchase_notifications/:gateway', :controller => 'purchase_notifications', :action => 'create', :requirements => {:gateway => /[a-z_]+/i}, as: :purchase_notifications

  post 'package_purchase_notifications/:gateway', :controller => 'package_purchase_notifications', :action => 'create', :requirements => {:gateway => /[a-z_]+/i}, as: :package_purchase_notifications

  get 'purchase_complete/:gateway', :controller => 'purchase_completions', :action => 'create', :requirements => {:gateway => /[a-z_]+/i}, as: :purchase_completions

  resources :instructors, :only => [:index, :show]

  resources :courses, :only => [:index, :show] do
    resource :purchase, :only => [:new, :create] do
      get 'renew' => 'purchases#renew'
      post 'renew_subscription' => 'purchases#renew_subscription'
    end
  end
  resources :gifts

  put '/courses/:course_id/enrolments/:id/unsubscribe', to: 'purchases#unsubscribe', as: :unsubscribe_course
  get '/courses/:course_id/purchases/:id/execute', to: 'purchases#execute', as: :payment_execute
  get '/gifts/:gift_id/execute', to: 'gifts#execute', as: :gift_execute

  get '/courses/:course_id/purchases/:id/renew_execute', to: 'purchases#renew_execute', as: :renew_payment_execute
  # put '/courses/:course_id/purchase/:id/payment', to: 'purchase#payment', as: :payment

  get 'course_select/:id', :controller => 'courses', :action => 'select', as: :select_course

  get 'courses/tags/:tag', :controller => 'courses', :action => 'index', as: :course_tags

  get 'courses/types/:course_type', :controller => 'courses', :action => 'index', as: :course_type

  get 'files/courses/:id/:style', :controller => 'courses', :action => 'photo', as: :course_photo
  get 'files/blogs/:id/:style', :controller => 'courses', :action => 'blogphoto', as: :blog_photo

  post '/tinymce_assets' => 'tinymce_assets#create'

  get 'tags', :controller => 'courses', :action => 'tag_cloud', as: :tags
  get 'blog', :controller => 'blogs', :action => 'index'

  get 'contest/', :controller => 'contests', :action => 'index'

  post 'blogs/savecomment', :controller => 'blogs', :action => 'savecomment'
  get 'blog/:id', :controller => 'blogs', :action => 'show', as: :inner_blog
  resources :packages, :only => [:index, :show] do
    resource :purchase, :controller => 'package_purchases', :only => [:new, :create]
  end

app/controllers/instructor/assignment_critiques_controller.rb
class Instructor::AssignmentCritiquesController < Instructor::BaseController
  
  def create
    logger.debug('-----------')
    logger.debug(params[:assignment_submission].to_yaml)
    logger.debug('-----------')
    
    critiques = params[:critique] if params.has_key?(:critique)
    if critiques
      if critiques.has_key?(:assignment)
        critiques[:assignment].each do |id, content|
          @submission_id = id
          if !content[:content].blank? || !content[:attachment].nil? ||  (content[:original] != content[:rearrangement])
            logger.debug("create critique")
            assignment = AssignmentSubmission.find_by_id(id)
            critique = assignment.critiques.new
            #critique.critiqueable_id = id, 
            #critique.critiqueable_type = 'AssignmentSubmission', 
            critique.user = current_user
            critique.comment = content[:content].blank? && !content[:attachment].nil? ? "File attached" : content[:content]
            
            if content[:original] != content[:rearrangement]
              critique.original_sequence = content[:original]
              critique.rearrangement_sequence = content[:rearrangement]
              critique.comment = 'Rearrangement' if critique.comment.blank? 
            end
            
            critique.save!
            if !content[:attachment].nil?
              @attachable = critique
              @attachment = build_attachment({:asset => content[:attachment]})
              @attachment.save!
            end
            critique.save!
          end
          logger.debug("--#{id}--#{content[:content]}--#{content[:content].blank?}")
        end
      end
      if critiques.has_key?(:attachment)
        critiques[:attachment].each do |id, content|
          logger.debug("--#{id}--#{content[:content]}--#{content[:content].blank?}")
          if !content[:content].blank? || !content[:attachment].nil?
            logger.debug("create critique #{id}")
            attachment = Attachment.find_by_id(id)
            critique = attachment.critiques.new
            #critique.critiqueable_type = 'Attachment', 
            #critique.critiqueable_id = id,
            critique.user = current_user
            critique.comment = content[:content].blank? && !content[:attachment].nil? ? "File attached" : content[:content]
            critique.save!
            if !content[:attachment].nil?
              @attachable = critique
              @attachment = build_attachment({:asset => content[:attachment]})
              @attachment.save!
            end
          end
        end
      end
    end
    
    @submission_id.nil? ? redirect_to(instructor_courses_path) : redirect_to(instructor_submission_path(@submission_id, :submitted => true))
  end

end

app/controllers/instructor/assignment_submissions_controller.rb
class Instructor::AssignmentSubmissionsController < Instructor::BaseController

  before_filter :find_scheduled_assignment, :only => :index
  before_filter :find_assignment_submission, :except => :index

  def index
    @assignment_submissions = @scheduled_assignment.submissions.paginate(:page => params[:page], :order => :updated_at)
  end

  def show
    
    if current_user.instructor?
    @assignment_submission.instructor_unread = 0
    @assignment_submission.save!
    end
    
  end

  def edit
    #abort('d')
  end
  
  def sequence
    @assignment_submission.instructor_rearrangement = params[:sequence]
    @assignment_submission.save!
    redirect_to instructor_submission_path(@assignment_submission)
  end

  def update
    if @assignment_submission.update_attributes(params[:assignment_submission])
      flash_and_redirect_to('The submission has been updated successfully', :notice, instructor_courses_path)
    else
      render(:action => 'edit')
    end
  end

  def delete
  end

  def destroy
    if @assignment_submission.delete!
      flash_and_redirect_to('The submission has been deleted successfully', :notice, instructor_courses_path)
    else
      render(:action => 'delete')
    end
  end

  protected

    def find_scheduled_assignment
      @scheduled_assignment = ScheduledAssignment.non_deleted.find(params[:scheduled_assignment_id])
    rescue ActiveRecord::RecordNotFound
      flash_and_redirect_to('The requested scheduled assignment does not exist', :error, instructor_root_path)
    end

    def find_assignment_submission
      @assignment_submission = AssignmentSubmission.non_deleted.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash_and_redirect_to('The requested assignment submission does not exist', :error, instructor_courses_path)
    end
    
    def setup_page
      super
      page_config do |page|
        page.body_tag_options[:class] = 'instructor'
        page.body_tag_options[:id] = 'assignmentsubmissions'
        page.secondary_navigation_section = :courses
        page.secondary_navigation = true
        page.title.unshift('Assignment Submissions')
      end
    end

end

app/controllers/instructor/assignment_submissions_controller_31july2015.rb
class Instructor::AssignmentSubmissionsController < Instructor::BaseController

  before_filter :find_scheduled_assignment, :only => :index
  before_filter :find_assignment_submission, :except => :index

  def index
    @assignment_submissions = @scheduled_assignment.submissions.paginate(:page => params[:page], :order => :updated_at)
  end

  def show
  end

  def edit
  end

  def update
    if @assignment_submission.update_attributes(params[:assignment_submission])
      flash_and_redirect_to('The submission has been updated successfully', :notice, instructor_courses_path)
    else
      render(:action => 'edit')
    end
  end

  def delete
  end

  def destroy
    if @assignment_submission.delete!
      flash_and_redirect_to('The submission has been deleted successfully', :notice, instructor_courses_path)
    else
      render(:action => 'delete')
    end
  end

  protected

    def find_scheduled_assignment
      @scheduled_assignment = ScheduledAssignment.non_deleted.find(params[:scheduled_assignment_id])
    rescue ActiveRecord::RecordNotFound
      flash_and_redirect_to('The requested scheduled assignment does not exist', :error, instructor_root_path)
    end

    def find_assignment_submission
      @assignment_submission = AssignmentSubmission.non_deleted.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash_and_redirect_to('The requested assignment submission does not exist', :error, instructor_courses_path)
    end
    
    def setup_page
      super
      page_config do |page|
        page.body_tag_options[:class] = 'instructor'
        page.body_tag_options[:id] = 'assignmentsubmissions'
        page.secondary_navigation_section = :courses
        page.secondary_navigation = true
        page.title.unshift('Assignment Submissions')
      end
    end

end

app/controllers/instructor/base_controller.rb
class Instructor::BaseController < ApplicationController

  layout 'instructor'
  before_filter :require_instructor_user
  before_filter :setup_page

  protected

    def setup_page
      page_config do |page|
        page.body_tag_options[:class] = 'instructor'
        page.primary_navigation_section = :instructor_area
        page.secondary_navigation = true
        page.title.unshift('Instructor Area')
      end
    end
end

app/controllers/instructor/lessons_comment_controller.rb
class Instructor::LessonsCommentController < Instructor::BaseController

 
  def delete
  	#@topic_id = {params[:topic_id]}
     @data = ActiveRecord::Base.connection.execute("update forum_topics set posts_count=posts_count-1 where id=#{params[:topic_id]}")
     @data = ActiveRecord::Base.connection.execute("delete from forum_posts where id=#{params[:id]}")
      respond_to do |format|
		msg = { :status => "ok", :message => "Success!", :html => "<b>...</b>" }
		format.json  { render :json => msg } # don't do msg.to_json
	  end
  end
end

app/views/instructors/_currently_teaching.html.erb
<% if !@instructor.nil? && @instructor.courses.visible.available.size > 0 -%>
  <div class="block block_upcoming_events">
    <div class="block_heading1">
      <span>Currently Teaching</span>
      <%= link_to ((content_tag :i, nil, class: :star) + 'See All'), courses_path(instructor: @instructor.id) %>
    </div>
    <div class=" block_content">
      <% @instructor.courses.visible.available.first(6).each_with_index do |course, i| -%>
        <h5><%= link_to(course.title, course_path(course), class: 'font_size_13 red') -%></h5></br>
      <% end -%>
    </div>
  </div>
<% end -%>

app/views/instructors/_featured.html.erb
<% @instructor = User.activated.visible.instructor.random.first %>

<div class="callout_box<%= " #{classes}" if local_assigns[:classes] -%><%= " fixed" unless local_assigns[:short].nil? -%>"><h4><%= link_to("See All", instructors_path) -%>Featured Instructor</h4>
  <div class="body padding_5 instructor">
    <% if @instructor.nil? -%>
      <p>No instructors available.</p>
    <% else -%>
      <%= link_to(image_tag(user_photo_path(:id => @instructor.id, :style => :w50xh60), :width => 50, :height => 60, :alt => @instructor.full_name), instructor_path(@instructor)) -%>
      <h5><%= link_to(@instructor.full_name, instructor_path(@instructor)) -%></h5>
      <%= truncate_html(@instructor.profile) -%>
      <% if !@instructor.vimeo_video_id.blank? %>
        <p><a class="fancybox-media" href="http://vimeo.com/<%= @instructor.vimeo_video_id -%>">View <%= "#{@instructor.given_name}'s" %> introduction video..</a></p>
      <% elsif !@instructor.youtube_video_id.blank? %>
        <p><a class="fancybox-media" href="http://www.youtube.com/watch?v=<%= @instructor.youtube_video_id -%>">View <%= "#{@instructor.given_name}'s" %> introduction video..</a></p>
      <% end %>
      <p><%= link_to("Read #{@instructor.given_name}'s Profile..", instructor_path(@instructor)) -%></p>
    <% end -%>
  </div>
</div>

app/views/instructors/_thumbnail.html.erb
<%= link_to(image_tag(user_photo_path(:id => thumbnail.id, :style => :large), :id => thumbnail_counter, :class => (((thumbnail_counter + 1) % 4) == 0) ? "last" : ""), instructor_path(thumbnail)) -%>

app/views/instructors/index-8-11-2016.html.erb
<% content_for :meta do %>
  <meta name="keywords" content="Photography Training, Photography Teacher, Photography Instructor" />
  <meta name="description" content="Get hands-on photography training from the best in the industry with professional teachers and instructors at The Compelling Image. Sign up today for your free lesson." />
<% end %>

<div class="content_wrapper"><!-- Main -->
  <div class="container content_bg"><!-- Container -->
    <div class="banner_with_instructor">
      <div class="banner_image">
        <%= instructor_image %>
      </div>
      <div class="instructor_title">
        <span>Instructor Directory</span>
      </div>
      <%unless @instructor.blank?%>
        <div class="instuctor_block">
          <%= link_to(image_tag(user_photo_path(:id => @instructor.id, :style => :w240xh230), :width => 240, :height => 230, :alt => @instructor.full_name), instructor_path(@instructor)) -%>
          <div class="description">
            <p>Instructor : <%= link_to(@instructor.full_name, instructor_path(@instructor)) -%></p>
            <% if @instructor.courses.size > 0 %>
              <p>Teaching:</p>
              <% @instructor.courses.visible.available.limit(3).each do |course| -%>
                <p><%= link_to(course.title, course_path(course)) -%></p>
              <% end -%>
            <% end %>
          </div><!-- description -->
        </div>
      <%end%>
    </div><!-- Banner -->

    <div class="inner_content_container">
      <div class='instructor_inner_container'>
        <div class="inner_content_left" style='width:100%'>
          <ul class="our_isntructors">
            <% if @instructors.size == 0 -%>
              <p>There are no instructors at this time.</p>
            <% else -%>
              <% @instructors.each_with_index do |instructor, i| -%>
                <li class="instructor">
                  <h5>
                    <%= link_to(instructor.full_name, instructor_path(instructor)) %>
                  </h5>
                  <%= link_to(image_tag(user_photo_path(:id => instructor.id, :style => :w145xh145), :width => 145, :height => 145, :alt => "Picture of #{instructor.full_name}"), instructor_path(instructor)) -%>
                    <p>
                      <%= link_to('Read Profile..', instructor_path(instructor)) -%>
                    </p>
                </li>
              <% end %>
            <% end %>
          </ul>

        </div><!-- Left Content -->
      </div><!-- instructor_inner_container-->

      <!-- <div class="inner_content_right">
        <%#= render(:partial => "courses/upcoming", :locals => {:classes => "margin_bottom_20"}) -%>
      </div> --><!-- Sidebar -->
    </div>

  </div><!-- Container -->
</div><!-- Main Content -->

app/views/instructors/index.html.erb
<% content_for :meta do %>
  <meta name="keywords" content="Photography Training, Photography Teacher, Photography Instructor" />
  <meta name="description" content="Get hands-on photography training from the best in the industry with professional teachers and instructors at The Compelling Image. Sign up today for your free lesson." />
<% end %>

<div class="content_wrapper margin-t-70"><!-- Main -->
  <div class="container content_bg"><!-- Container -->
    <div class="banner_with_instructor">
      <div class="banner_image">
        <%= instructor_image %>
      </div>
      <div class="instructor_title">
        <span>Instructor Directory</span>
      </div>
      <%unless @instructor.blank?%>
        <div class="instuctor_block">
          <%= link_to(image_tag(user_photo_path(:id => @instructor.id, :style => :w240xh230), :width => 240, :height => 230, :alt => @instructor.full_name), instructor_path(@instructor)) -%>
          <div class="description">
            <p>Instructor : <%= link_to(@instructor.full_name, instructor_path(@instructor)) -%></p>
            <% if @instructor.courses.size > 0 %>
              <p>Teaching:</p>
              <% @instructor.courses.visible.available.limit(3).each do |course| -%>
                <p><%= link_to(course.title, course_path(course)) -%></p>
              <% end -%>
            <% end %>
          </div><!-- description -->
        </div>
      <%end%>
    </div><!-- Banner -->

    <div class="inner_content_container">
      <div class='instructor_inner_container'>
        <div class="inner_content_left" style='width:100%'>
          <ul class="our_isntructors">
            <% if @instructors.size == 0 -%>
              <p>There are no instructors at this time.</p>
            <% else -%>
              <% @instructors.each_with_index do |instructor, i| -%>
                <li class="instructor">
                  <h5>
                    <%= link_to(instructor.full_name, instructor_path(instructor)) %>
                  </h5>
                  <%= link_to(image_tag(user_photo_path(:id => instructor.id, :style => :w145xh145), :width => 145, :height => 145, :alt => "Picture of #{instructor.full_name}"), instructor_path(instructor)) -%>
                    <p>
                      <%= link_to('Read Profile..', instructor_path(instructor)) -%>
                    </p>
                </li>
              <% end %>
            <% end %>
          </ul>

        </div><!-- Left Content -->
      </div><!-- instructor_inner_container-->

      <!-- <div class="inner_content_right">
        <%#= render(:partial => "courses/upcoming", :locals => {:classes => "margin_bottom_20"}) -%>
      </div> --><!-- Sidebar -->
    </div>

  </div><!-- Container -->
</div><!-- Main Content -->

app/views/instructors/show.html.erb
<% content_for :meta do %>
  <% unless @instructor.meta_description.nil? %>
    <meta name="description" content="<%= @instructor.meta_description -%>" />
  <% end %>
  <% unless @instructor.meta_keywords.nil? %>
    <meta name="keywords" content="<%= @instructor.meta_keywords -%>" />
  <% end %>
<% end %>
<%= stylesheet_link_tag 'style', 'responsive' %>

<div class="container content_bg"><!-- Container -->
  <div class="banner_with_instructor">
    <div class="banner_image">
      <%= instructor_image %>
    </div>
    <div class="instructor_title">
      <span>Instructor Directory</span>
    </div>
    <div class="instuctor_block">
      <%= image_tag @instructor.photo.url, alt: "#{@instructor.full_name} Photography" %>
      <div class="description">
        <p>Instructor:</p>
        <ul>
          <li><%= link_to(@instructor.full_name, instructor_path(@instructor)) %></li>
          <li><%= "Teaching:" if @instructor.courses.size > 0 %></li>
          <% @instructor.courses.visible.available.limit(2).each do |course| -%>
            <li><%= link_to(course.title, course_path(course)) -%></li>
          <% end -%>
          <% if @instructor.courses.visible.available.size > 3 %>
            <li>And <%= @instructor.courses.size - 3 -%> <%= link_to 'more courses', courses_path(instructor: @instructor.id)%>..</li>
          <% end %>
        </ul>
      </div>
    </div>
  </div><!-- Banner -->

  <div class="inner_content_container">
    <div class="inner_content_left">
      <div class="page_title"><%= @instructor.full_name %></div>
      <p><%= @instructor.profile.html_safe %>
    </div><!-- Left Content -->


    <div class="inner_content_right">
      <%#= render(:partial => "courses/upcoming", :locals => {:classes => "margin_bottom_20"}) -%>
      <%= render(:partial => "instructors/currently_teaching", :locals => {:classes => "margin_bottom_20"}) -%>
    </div><!-- Sidebar -->
  </div>
</div>

app/views/instructors/show.html_27_july_2015.erb
<% content_for :meta do %>
  <% unless @instructor.meta_description.nil? %>
    <meta name="description" content="<%= @instructor.meta_description -%>" />
  <% end %>
  <% unless @instructor.meta_keywords.nil? %>
    <meta name="keywords" content="<%= @instructor.meta_keywords -%>" />
  <% end %>
<% end %>
<%= stylesheet_link_tag 'style', 'responsive' %>

<div class="container content_bg"><!-- Container -->
  <div class="banner_with_instructor">
    <div class="banner_image">
      <%= instructor_image %>
    </div>
    <div class="instructor_title">
      <span>Instructor Directory</span>
    </div>
    <div class="instuctor_block">
      <%= image_tag @instructor.photo.url, alt: "#{@instructor.full_name} Photography" %>
      <div class="description">
        <p>Instructor:</p>
        <ul>
          <li><%= link_to(@instructor.full_name, instructor_path(@instructor)) %></li>
          <li><%= "Teaching:" if @instructor.courses.size > 0 %></li>
          <% @instructor.courses.visible.available.limit(3).each do |course| -%>
            <li><%= link_to(course.title, course_path(course)) -%></li>
          <% end -%>
          <% if @instructor.courses.visible.available.size > 3 %>
            <li>And <%= @instructor.courses.size - 3 -%> <%= link_to 'more courses', courses_path(instructor: @instructor.id)%>..</li>
          <% end %>
        </ul>
      </div>
    </div>
  </div><!-- Banner -->

  <div class="inner_content_container">
    <div class="inner_content_left">
      <div class="page_title"><%= @instructor.full_name %></div>
      <p><%= @instructor.profile.html_safe %>
    </div><!-- Left Content -->


    <div class="inner_content_right">
      <%#= render(:partial => "courses/upcoming", :locals => {:classes => "margin_bottom_20"}) -%>
      <%= render(:partial => "instructors/currently_teaching", :locals => {:classes => "margin_bottom_20"}) -%>
    </div><!-- Sidebar -->
  </div>
</div>