config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', :constraints => lambda { |request|
    User.find_by(id: request.session[:user_id]).try(:administrator?)
  }

  namespace :administrator do
    get 'contest_descriptions/new'
  end

  namespace :administrator do
    get 'contest_descriptions/index'
  end

  namespace :administrator do
    get 'contest_descriptions/create'
  end

  namespace :administrator do
    resources :testimonials do
      member do
        get 'delete'
      end
    end
    resource :special
    resources :reports, only: [:new, :create]
    resources :users do
      member do
        get 'delete'
      end
      collection do
        get 'export'
      end
      resource :activation, :only => :create
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
    end
    get :change_image_order, to: 'attachments#change_image_order'

    resources :attachments, :except => [:index, :new, :create] do
      member do
        get 'delete'
      end
      resources :critiques, :only => [:new, :create]
    end

    resources :courses do
      member do
        get 'delete'
      end

      resources :attachments, :only => [:index, :new, :create]
      resources :forum_topics, :only => [:index, :new, :create]
      resources :lessons, :only => [:index, :new, :create]
      #resources :scheduled_courses, :only => [:index, :new,:create]
      resources :scheduled_courses, only: [:index]
    end

    resources :blogs do
      member do
        get 'delete'
      end

      resources :attachments, :only => [:index, :new, :create]
    end

    resources :certificate, only: [:index, :generate] do
      collection do
        post 'generate'
      end
    end
    resources :renewals, only: [:index, :create, :destroy]

    resources :workshops do
      member do
        get 'delete'
      end
    end

    resources :packages do
      member do
        get 'delete'
      end
      resources :attachments, :only => [:index, :new, :create]
    end

    resources :banner_images, only: [:index, :create, :destroy]
    resources :student_galleries, only: [:index, :create, :destroy]
    resources :contests, only: [:index, :create, :destroy, :new]
    resources :contest_descriptions, only: [:index, :create, :new, :edit]

    resources :settings

    resources :forum_topics do
      member do
        get 'delete'
      end
      resources :posts, :controller => 'forum_posts', :only => [:new, :create]
    end

    resources :lessons, :except => [:index, :new, :create] do
      member do
        get 'delete'
      end
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
      resources :assignments, :only => [:index, :new, :create]
    end

    resources :assignments, :except => [:index, :new, :create] do
      member do
        get 'delete'
      end
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
      resources :rearrangements
    end

    resources :rearrangements, :except => [:index, :new, :create] do
      member do
        get 'delete'
      end
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
    end

    resources :scheduled_assignments, :only => :show do
      resources :submissions, :controller => 'assignment_submissions', :only => :index
    end

    resources :assignment_submissions, :except => [:index, :new, :create] do
      member do
        get 'delete'
      end
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
      resources :critiques, :only => [:new, :create]
    end

    resources :scheduled_courses, :only => [:show] do
      resources :enrolments, :only => [:index, :new, :create]
    end

    resources :critiques, :only => [:edit, :update, :destroy] do
      member do
        get 'delete'
      end
    end

    resources :enrolments, :only => [:edit, :update, :destroy] do
      member do
        get 'delete'
      end
    end

    resources :forum_posts, :only => [:edit, :update, :destroy] do
      member do
        get 'delete'
      end
    end

    resources :exchange_rates, :except => :show do
      member do
        get 'delete'
      end
    end

    resources :partners do
      member do
        get 'delete'
      end
    end

    resources :gifts
  end

  namespace :instructor do
    resource :account, :controller => 'users', :only => [:edit, :update]
    resources :attachments do
      member do
        get 'delete'
      end
    end

    resources :lessons_comment, :only => [:delete] do
      member do
        get 'delete'
      end
    end
    resources :lessons, :only => :show
    resources :assignments, :only => :show
    resources :updates, :only => [:index]
    resources :mystudents, :only => [:index] do
      member do
        get 'courses'
      end
    end
    resources :courses, :only => :index do
      resources :scheduled_courses, :only => :index
    end
    resources :scheduled_courses, :only => [:show, :destroy] do
      member do
        get 'delete'
      end
      resources :enrolments, :only => [:index, :new, :create]
    end
    resources :forum_topics, :except => :destroy do
      resources :posts, :controller => 'forum_posts', :only => [:new, :create]
    end

    resources :submissions, :controller => 'assignments_submissions', :except => [:new, :create] do
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
      resources :critiques, :controller => 'assignment_critiques', :only => [:new, :create]
      #resource :sequence
    end
    resources :forum_posts, :only => [:edit, :update]
    get 'sequence/:id', :controller => "assignment_submissions", :action => 'sequence', as: :instructor_sequence

    get 'lessons/:lesson_id/attachments/new', :controller => "upload_video", :action => 'new', :as => 'lession'
    get 'lessons/:lesson_id/attachments', :controller => "upload_video", :action => 'new', :as => 'lession1'
    post 'lessons/:lesson_id/attachments', :controller => "upload_video", :action => 'create', :as => 'path_video'
    #
    get 'lessons/:lesson_id/upload', :controller => "upload_video", :action => 'upload', :as => 'inst_assignment'
    get 'lessons/:lesson_id', :controller => "upload_video", :action => 'upload', :as => 'inst_assignment1'
    post 'lessons/:lesson_id', :controller => "upload_video", :action => 'upload_video', :as => 'path_video_attach'
  end
  get 'courses/fulldownload', :controller => 'courses', :action => 'fulldownload'

  namespace :student do
    resource :account, :controller => 'users', :only => [:edit, :update]
    resources :attachments do
      member do
        get 'delete'
      end
      collection do
        post 'order'
      end
    end

    resources :courses, :controller => 'scheduled_courses' do
      resources :lessons, :controller => 'scheduled_lessons', :only => :show
      resources :reviews, only: [:new, :create, :destroy]
    end

    resources :assignments, :controller => 'scheduled_assignments' do
      resources :submissions, :controller => 'assignment_submissions', :only => [:new, :create]
    end

    resources :submissions, :controller => 'assignment_submissions', :except => [:new, :create] do
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
          get 'sequence'
        end
      end
      resources :critiques do
        resources :critiques, :only => [:new, :create]
      end
    end

    resources :forum_topics, :except => :destroy do
      resources :posts, :controller => 'forum_posts', :only => [:new, :create]
    end
    resources :updates, :only => [:index]
    resources :forum_posts, :only => [:edit, :update]

    get 'sequence/:id', :controller => "assignment_submissions", :action => 'sequence', as: :student_sequence

    get 'lessons/:lesson_id/assignments/:assignments_id/attachments/new', :controller => "upload_video", :action => 'new', :as => 'stdunt_post_video'
    get 'lessons/:lesson_id/assignments/:assignments_id/attachments', :controller => "upload_video", :action => 'new', :as => 'stdunt_post_video1'
    post 'lessons/:lesson_id/assignments/:assignments_id/attachments', :controller => "upload_video", :action => 'create', :as => 'post_video'
  end
  get 'attachments/:id/:style.:format', :controller => 'attachments', :action => 'download', as: :attachment_download

  get "paypal" => "purchase_notifications#paypal", :path => "purchase_notifications/paypal"

  post 'purchase_notifications/:gateway', :controller => 'purchase_notifications', :action => 'create', :requirements => {:gateway => /[a-z_]+/i}, as: :purchase_notifications

  post 'package_purchase_notifications/:gateway', :controller => 'package_purchase_notifications', :action => 'create', :requirements => {:gateway => /[a-z_]+/i}, as: :package_purchase_notifications

  get 'purchase_complete/:gateway', :controller => 'purchase_completions', :action => 'create', :requirements => {:gateway => /[a-z_]+/i}, as: :purchase_completions

  resources :instructors, :only => [:index, :show]

  resources :courses, :only => [:index, :show] do
    resource :purchase, :only => [:new, :create] do
      get 'renew' => 'purchases#renew'
      post 'renew_subscription' => 'purchases#renew_subscription'
    end
  end
  resources :gifts

  put '/courses/:course_id/enrolments/:id/unsubscribe', to: 'purchases#unsubscribe', as: :unsubscribe_course
  get '/courses/:course_id/purchases/:id/execute', to: 'purchases#execute', as: :payment_execute
  get '/gifts/:gift_id/execute', to: 'gifts#execute', as: :gift_execute

app/models/assignment.rb
class Assignment < ActiveRecord::Base

  belongs_to :lesson
  has_many :rearrangements

  with_options :dependent => :destroy do |o|
    o.has_many :scheduled_assignments, -> { where(:deleted_at => nil) }
    o.has_many :deleted_scheduled_assignments, -> {where("#{quoted_column_name('deleted_at')} IS NOT NULL")}, :class_name => 'ScheduledAssignment'
  end

  acts_as_attachable
  acts_as_deletable

  attr_accessible :title, :summary, :description, :duration, :starts_after

  validates_presence_of :title

  with_options :allow_blank => true do |o|
    o.validates_length_of :title, :maximum => 255
    o.validates_length_of :summary, :maximum => 65535
    o.validates_length_of :description, :maximum => 16777215
  end


  validate :lesson_must_not_be_deleted, :on => :create

  delegate :course, :to => :lesson

  def self.schedule_for!(scheduled_lesson)
    scheduled_lesson.lesson.assignments.all.each do |assignment|
      unless scheduled_lesson.scheduled_assignments.find_by_assignment_id(assignment.id)
        scheduled_lesson.scheduled_assignments.create! { |s| s.assignment = assignment }
      end
    end
  end

  def attachable?(user)
    !deleted? && lesson.attachable?(user)
  end

  def active?
    !deleted?
  end

  protected

    def lesson_must_not_be_deleted
      errors.add(:lesson, 'must not be deleted') unless lesson.nil? || !lesson.deleted?
    end
end

app/controllers/administrator/assignments_controller.rb
class Administrator::AssignmentsController < Administrator::BaseController

  before_filter :find_lesson, :only => [ :index, :new, :create ]
  before_filter :find_assignment, :except => [ :index, :new, :create ]

  def index
    @assignments = @lesson.assignments.paginate(:page => params[:page])
  end

  def show
  end

  def new
    @assignment = @lesson.assignments.build
  end

  def create
    @assignment = @lesson.assignments.build(params[:assignment])

    if @assignment.save
      flash_and_redirect_to('You have successfully created a new assignment', :notice, administrator_lesson_assignments_path(@lesson))
    else
      render(:action => 'new')
    end
  end

  def edit
  end

  def update
    if @assignment.update_attributes(params[:assignment])
      flash_and_redirect_to('The assignment has been updated successfully', :notice, administrator_lesson_assignments_path(@assignment.lesson))
    else
      render(:action => 'edit')
    end
  end

  def delete
  end

  def destroy
    if @assignment.delete!
      flash_and_redirect_to('Your assignment has been deleted successfully', :notice, administrator_lesson_assignments_path(@assignment.lesson))
    else
      render(:action => 'delete')
    end
  end

  protected

    def find_lesson
      @lesson = Lesson.non_deleted.find(params[:lesson_id])
    rescue ActiveRecord::RecordNotFound
      flash_and_redirect_to('The requested lesson does not exist', :error, administrator_lessons_path)
    end

    def find_assignment
      @assignment = Assignment.non_deleted.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash_and_redirect_to('The requested assignment does not exist', :error, administrator_lessons_path)
    end

end

app/controllers/administrator/lessons_controller.rb
class Administrator::LessonsController < Administrator::BaseController

  before_filter :find_course, :only => [ :index, :new, :create ]
  before_filter :find_lesson, :except => [ :index, :new, :create ]

  def index
    @lessons = @course.lessons.paginate(:page => params[:page], :order => 'position ASC, title ASC')
  end

  def show
  end

  def new
    @lesson = @course.lessons.build
  end

  def create
    @lesson = @course.lessons.build(params[:lesson])

    if @lesson.save
      flash_and_redirect_to('You have successfully created a new lesson', :notice, administrator_course_lessons_path(@course))
    else
      render(:action => 'new')
    end
  end

  def edit
  end

  def update
    if @lesson.update_attributes(params[:lesson])
      flash_and_redirect_to('You have successfully updated the lesson', :notice, administrator_course_lessons_path(@lesson.course))
    else
      render(:action => 'edit')
    end
  end

  def delete
  end

  def destroy
    if @lesson.delete!
      flash_and_redirect_to('Your lesson has been deleted successfully', :notice, administrator_course_lessons_path(@lesson.course))
    else
      render(:action => 'delete')
    end
  end

  protected

    def find_course
      @course = Course.non_deleted.find(params[:course_id])
    rescue ActiveRecord::RecordNotFound
      flash_and_redirect_to('The requested course does not exist', :error, administrator_courses_path)
    end

    def find_lesson
      @lesson = Lesson.non_deleted.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash_and_redirect_to('The requested lesson does not exist', :error, administrator_courses_path)
    end
    
    def setup_page
      page_config do |page|
        super
        page.secondary_navigation_section = :courses
        page.title.unshift('Lessons')
      end
    end

end

app/controllers/instructor/assignments_controller.rb
class Instructor::AssignmentsController < Instructor::BaseController

  include Theia::ActsAsDiscussable::Controller
  before_filter :find_assignment

  def show
    @check_login =user_role_root_path
    @assg_id =@assignment.id
    @submissions = AssignmentSubmission.where(scheduled_assignment_id: @assignment.scheduled_assignments)
    @course = @assignment.lesson.course
    @scheduled_assignment = @assignment.scheduled_assignments.last
    @forum_topics = ForumTopic.where(discussable_id: @assignment.scheduled_assignments.pluck(:id), discussable_type: 'ScheduledAssignment')
    @forum_topic = @forum_topics.first
    unless @forum_topic.blank?
      @forum_post = build_forum_post
    end
  end
  

  protected

  def setup_page
    super
    page_config do |page|
      page.body_tag_options[:id] = 'instructor'
      page.body_tag_options[:class] = 'columns'
      page.secondary_navigation_section = :courses
      page.secondary_navigation = true
      page.title.unshift('Assignment')
    end
  end

  def find_assignment
    if (@assignment = Assignment.find_by_id(params[:id])).nil?
      flash_and_redirect_to('The requested assignment does not exist', :error, user_role_root_path)
    end
  end
end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < Instructor::BaseController

  include Theia::ActsAsDiscussable::Controller

  def show
    @lesson = Lesson.find_by_id(params[:id])
    #@lesson = @scheduled_lesson.lesson
    @course = @lesson.course
    @check_login =user_role_root_path
   # abort(@check_login)
    if (@lesson.nil?)
      flash_and_redirect_to('The lesson you requested does not exist', :error, user_role_root_path)
    end

    @forum_topics = ForumTopic.where(discussable_id: @lesson.scheduled_lessons.pluck(:id), discussable_type: 'ScheduledLesson')
    @forum_topic = @forum_topics.first
    unless @forum_topic.nil?
      @forum_post = build_forum_post
    end
  end

  protected

  def setup_page
    super
    page_config do |page|
      page.body_tag_options[:id] = 'instructor'
      page.body_tag_options[:class] = 'columns'
      page.secondary_navigation_section = :courses
      page.secondary_navigation = true
      page.title.unshift('Lesson')
    end
  end
end

app/views/administrator/assignments/lessons/_new_and_edit_form.html.erb
<div class="grid_16 margin_top_20 alpha omega">
  <%= uni_form_for(lesson, :url => path, :html => { :multipart => true }) do |f| %>
    <%= error_messages(@lesson) %>
    <% f.fieldset(:type => "block", :legend => "Lesson Details") do %>
      <%= f.text_field(:title, :size => '30', :label => "Title", :required => true, :style => "width: 99%;") %>
      <%= f.text_area(:description, :size => '60x5', :class => 'widgEditor', :label => "Description", :style => "width: 99%; height: 300px;") -%>
      <%= f.text_field(:position, :size => 5, :label => "Position", :required => true, :style => "width: 75px;") -%>
      <%= f.file_field(:vimeo_asset, :label => "Video Upload") -%>
      <%- if lesson.vimeo_asset? && (lesson.delete_vimeo ==0) -%>
        <%= f.check_box(:delete_vimeo, :label => "Delete Vimeo") %>
        <%#=  Lesson.get_thumbnail(lesson.vimeo_asset) %>
        <%= image_tag(Lesson.get_thumbnail(lesson.vimeo_asset), alt:  'Video', title:  'Current video',  style:  "padding: 10px;") %>
      <%- end -%>
  
      <%= f.file_field(:photo, :label => "Photo") -%>
      <%- if lesson.photo? && !lesson.photo.dirty? -%>
        <%= f.check_box(:delete_photo, :label => "Delete photo") %>
        <%#= image_tag(lesson_photo_path(:id => lesson.id, :style => :medium), :alt => 'Photo', :title => 'Current photo', :style => "padding: 10px;") %>
        <%= image_tag(lesson.photo_s3_url(:medium), alt:  'Photo', title:  'Current photo',  style:  "padding: 10px;") %>
      <%- end -%>
    <% end %>
    <div class="clear">&nbsp;</div><br />
    <p class="buttons"><%= pretty_button (lesson.new_record? ? "Create" : "Update"), {:icon_path => "icons/tick.png"} %>
  <% end %>
</div>

app/views/administrator/assignments/lessons/delete.html.erb
<dl>
  <dt>Course</dt>
  <dd><%= h(@lesson.course.title) %></dd>
  <dt>Title</dt>
  <dd><%= h(@lesson.title) %></dd>
  <dt>Summary</dt>
  <dd><%= h(@lesson.summary) %></dd>
</dl>
<%= form_for([ :administrator, @lesson ], :html => { :method => :delete }) do |f| %>
  <%= f.submit('Delete', :name => nil) %>
<% end %>

app/views/administrator/assignments/lessons/edit.html.erb
<%= render(:partial => 'new_and_edit_form', :locals => { :lesson => @lesson, :path => polymorphic_path([ :administrator, @lesson ]) }) -%>

app/views/administrator/assignments/lessons/index.html.erb
<div class="grid_11 margin_top_20 alpha">
  <h6>Lessons for <%= h(@course.title) -%></h6>
  <% unless @lessons.empty? %>
    <table summary="List of students lessons" class="pretty">
      <thead>
        <tr>
          <th></th>
          <th class="centred">Title</th>
          <th class="centred">Assignments</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% @lessons.each do |lesson| %>
          <tr>
            <td><%= lesson.position -%></td>
            <td class="centred"><%= link_to(h(lesson.title), edit_administrator_lesson_path(lesson)) -%></td>
            <td class="centred"><%= link_to(lesson.assignments.size, administrator_lesson_assignments_path(lesson), :rel => "There #{lesson.assignments.size == 1 ? 'is' : 'are'} #{pluralize(lesson.assignments.size, "assignment")} for this lesson") -%></td>
            <td align="right">
              <%= link_to(image_tag("icons/pencil.png", :alt => "Edit lesson"), edit_administrator_lesson_path(lesson), :rel => "Edit lesson") -%>
              &nbsp;
              <%= link_to(image_tag("icons/page_white_picture.png", :alt => "Assignments"), administrator_lesson_assignments_path(lesson), :rel => "Create, View or Edit Assignments") -%>
              &nbsp;
              <%= link_to(image_tag("icons/picture.png", :alt => "Attachments"), polymorphic_attachments_path(lesson), :rel => "Create, View or Edit Attachments") %>
              &nbsp;
              <%= link_to(image_tag("icons/delete.png", :alt => "Delete lesson"), delete_administrator_lesson_path(lesson)) -%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate(@lessons) %>
  <% else %>
    <p>No lessons exist for this course.</p>
  <% end %>
</div>
<div class="grid_5 margin_top_20 omega">
  <p class="buttons">
    <%= pretty_button_link "Create new lesson", new_administrator_course_lesson_path(@course), {:icon_path => "icons/add.png"} %>
  </p>
  <div class="clear">&nbsp;</div><br />
</div>
<div class="clear">&nbsp;</div>

app/views/administrator/assignments/lessons/new.html.erb
<%= render(:partial => 'new_and_edit_form', :locals => { :lesson => @lesson, :path => polymorphic_path([ :administrator, @course, @lesson ]) }) -%>

app/views/administrator/assignments/lessons/show.html.erb
<div class="grid_11 margin_top_20 alpha">
  <h4><%= @lesson.course.title %></h4>
  <h5><%= @lesson.title -%></h5>
  <hr />
  <%= interpolate_attachments(@lesson.description, @lesson.attachments, 620, 440).html_safe -%>
</div>
<div class="grid_5 margin_top_20 omega">
  <p><%= link_to('Edit this lesson', edit_administrator_lesson_path(@lesson)) %></p>
  <%= render(:partial => "student/attachments/attachments", :locals => {:classes => "margin_bottom_20", :title => 'Examples', :attachments => @lesson.attachments}) -%>
</div>
<div class="clear">&nbsp;</div>