config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', :constraints => lambda { |request|
    User.find_by(id: request.session[:user_id]).try(:administrator?)
  }

  namespace :administrator do
    get 'contest_descriptions/new'
  end

  namespace :administrator do
    get 'contest_descriptions/index'
  end

  namespace :administrator do
    get 'contest_descriptions/create'
  end

  namespace :administrator do
    resources :testimonials do
      member do
        get 'delete'
      end
    end
    resource :special
    resources :reports, only: [:new, :create]
    resources :users do
      member do
        get 'delete'
      end
      collection do
        get 'export'
      end
      resource :activation, :only => :create
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
    end
    get :change_image_order, to: 'attachments#change_image_order'

    resources :attachments, :except => [:index, :new, :create] do
      member do
        get 'delete'
      end
      resources :critiques, :only => [:new, :create]
    end

    resources :courses do
      member do
        get 'delete'
      end

      resources :attachments, :only => [:index, :new, :create]
      resources :forum_topics, :only => [:index, :new, :create]
      resources :lessons, :only => [:index, :new, :create]
      #resources :scheduled_courses, :only => [:index, :new,:create]
      resources :scheduled_courses, only: [:index]
    end

    resources :blogs do
      member do
        get 'delete'
      end

      resources :attachments, :only => [:index, :new, :create]
    end

    resources :certificate, only: [:index, :generate] do
      collection do
        post 'generate'
      end
    end
    resources :renewals, only: [:index, :create, :destroy]

    resources :workshops do
      member do
        get 'delete'
      end
    end

    resources :packages do
      member do
        get 'delete'
      end
      resources :attachments, :only => [:index, :new, :create]
    end

    resources :banner_images, only: [:index, :create, :destroy]
    resources :student_galleries, only: [:index, :create, :destroy]
    resources :contests, only: [:index, :create, :destroy, :new]
    resources :contest_descriptions, only: [:index, :create, :new, :edit]

    resources :settings

    resources :forum_topics do
      member do
        get 'delete'
      end
      resources :posts, :controller => 'forum_posts', :only => [:new, :create]
    end

    resources :lessons, :except => [:index, :new, :create] do
      member do
        get 'delete'
      end
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
      resources :assignments, :only => [:index, :new, :create]
    end

    resources :assignments, :except => [:index, :new, :create] do
      member do
        get 'delete'
      end
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
      resources :rearrangements
    end

    resources :rearrangements, :except => [:index, :new, :create] do
      member do
        get 'delete'
      end
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
    end

    resources :scheduled_assignments, :only => :show do
      resources :submissions, :controller => 'assignment_submissions', :only => :index
    end

    resources :assignment_submissions, :except => [:index, :new, :create] do
      member do
        get 'delete'
      end
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
      resources :critiques, :only => [:new, :create]
    end

    resources :scheduled_courses, :only => [:show] do
      resources :enrolments, :only => [:index, :new, :create]
    end

    resources :critiques, :only => [:edit, :update, :destroy] do
      member do
        get 'delete'
      end
    end

    resources :enrolments, :only => [:edit, :update, :destroy] do
      member do
        get 'delete'
      end
    end

    resources :forum_posts, :only => [:edit, :update, :destroy] do
      member do
        get 'delete'
      end
    end

    resources :exchange_rates, :except => :show do
      member do
        get 'delete'
      end
    end

    resources :partners do
      member do
        get 'delete'
      end
    end

    resources :gifts
  end

  namespace :instructor do
    resource :account, :controller => 'users', :only => [:edit, :update]
    resources :attachments do
      member do
        get 'delete'
      end
    end

    resources :lessons_comment, :only => [:delete] do
      member do
        get 'delete'
      end
    end
    resources :lessons, :only => :show
    resources :assignments, :only => :show
    resources :updates, :only => [:index]
    resources :mystudents, :only => [:index] do
      member do
        get 'courses'
      end
    end
    resources :courses, :only => :index do
      resources :scheduled_courses, :only => :index
    end
    resources :scheduled_courses, :only => [:show, :destroy] do
      member do
        get 'delete'
      end
      resources :enrolments, :only => [:index, :new, :create]
    end
    resources :forum_topics, :except => :destroy do
      resources :posts, :controller => 'forum_posts', :only => [:new, :create]
    end

    resources :submissions, :controller => 'assignments_submissions', :except => [:new, :create] do
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
      resources :critiques, :controller => 'assignment_critiques', :only => [:new, :create]
      #resource :sequence
    end
    resources :forum_posts, :only => [:edit, :update]
    get 'sequence/:id', :controller => "assignment_submissions", :action => 'sequence', as: :instructor_sequence

    get 'lessons/:lesson_id/attachments/new', :controller => "upload_video", :action => 'new', :as => 'lession'
    get 'lessons/:lesson_id/attachments', :controller => "upload_video", :action => 'new', :as => 'lession1'
    post 'lessons/:lesson_id/attachments', :controller => "upload_video", :action => 'create', :as => 'path_video'
    #
    get 'lessons/:lesson_id/upload', :controller => "upload_video", :action => 'upload', :as => 'inst_assignment'
    get 'lessons/:lesson_id', :controller => "upload_video", :action => 'upload', :as => 'inst_assignment1'
    post 'lessons/:lesson_id', :controller => "upload_video", :action => 'upload_video', :as => 'path_video_attach'
  end
  get 'courses/fulldownload', :controller => 'courses', :action => 'fulldownload'

  namespace :student do
    resource :account, :controller => 'users', :only => [:edit, :update]
    resources :attachments do
      member do
        get 'delete'
      end
      collection do
        post 'order'
      end
    end

    resources :courses, :controller => 'scheduled_courses' do
      resources :lessons, :controller => 'scheduled_lessons', :only => :show
      resources :reviews, only: [:new, :create, :destroy]
    end

    resources :assignments, :controller => 'scheduled_assignments' do
      resources :submissions, :controller => 'assignment_submissions', :only => [:new, :create]
    end

    resources :submissions, :controller => 'assignment_submissions', :except => [:new, :create] do
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
          get 'sequence'
        end
      end
      resources :critiques do
        resources :critiques, :only => [:new, :create]
      end
    end

    resources :forum_topics, :except => :destroy do
      resources :posts, :controller => 'forum_posts', :only => [:new, :create]
    end
    resources :updates, :only => [:index]
    resources :forum_posts, :only => [:edit, :update]

    get 'sequence/:id', :controller => "assignment_submissions", :action => 'sequence', as: :student_sequence

    get 'lessons/:lesson_id/assignments/:assignments_id/attachments/new', :controller => "upload_video", :action => 'new', :as => 'stdunt_post_video'
    get 'lessons/:lesson_id/assignments/:assignments_id/attachments', :controller => "upload_video", :action => 'new', :as => 'stdunt_post_video1'
    post 'lessons/:lesson_id/assignments/:assignments_id/attachments', :controller => "upload_video", :action => 'create', :as => 'post_video'
  end
  get 'attachments/:id/:style.:format', :controller => 'attachments', :action => 'download', as: :attachment_download

  get "paypal" => "purchase_notifications#paypal", :path => "purchase_notifications/paypal"

  post 'purchase_notifications/:gateway', :controller => 'purchase_notifications', :action => 'create', :requirements => {:gateway => /[a-z_]+/i}, as: :purchase_notifications

  post 'package_purchase_notifications/:gateway', :controller => 'package_purchase_notifications', :action => 'create', :requirements => {:gateway => /[a-z_]+/i}, as: :package_purchase_notifications

  get 'purchase_complete/:gateway', :controller => 'purchase_completions', :action => 'create', :requirements => {:gateway => /[a-z_]+/i}, as: :purchase_completions

  resources :instructors, :only => [:index, :show]

  resources :courses, :only => [:index, :show] do
    resource :purchase, :only => [:new, :create] do
      get 'renew' => 'purchases#renew'
      post 'renew_subscription' => 'purchases#renew_subscription'
    end
  end
  resources :gifts

  put '/courses/:course_id/enrolments/:id/unsubscribe', to: 'purchases#unsubscribe', as: :unsubscribe_course
  get '/courses/:course_id/purchases/:id/execute', to: 'purchases#execute', as: :payment_execute
  get '/gifts/:gift_id/execute', to: 'gifts#execute', as: :gift_execute

app/controllers/administrator/activations_controller.rb
class Administrator::ActivationsController < Administrator::BaseController

  def create
    @user = User.pending.find(params[:user_id])
    @user.activate_without_confirmation!

    if @user.activated?
      flash_and_redirect_to('You have successfully activated the user account', :notice, administrator_users_path)
    else
      render(:action => 'new')
    end

  rescue ActiveRecord::RecordNotFound
    flash_and_redirect_to('The requested user account does not exist.', :error, administrator_users_path)
  end

end

app/controllers/administrator/assignment_submissions_controller.rb
class Administrator::AssignmentSubmissionsController < Administrator::BaseController

  before_filter :find_scheduled_assignment, :only => :index
  before_filter :find_assignment_submission, :except => :index

  def index
    @assignment_submissions = @scheduled_assignment.submissions.paginate(:page => params[:page], :order => :updated_at)
  end

  def show
  end

  def edit
  end

  def update
    if @assignment_submission.update_attributes(params[:assignment_submission])
      flash_and_redirect_to('The submission has been updated successfully', :notice, administrator_scheduled_assignment_submissions_path(@assignment_submission.scheduled_assignment))
    else
      render(:action => 'edit')
    end
  end

  def delete
  end

  def destroy
    if @assignment_submission.delete!
      flash_and_redirect_to('The submission has been deleted successfully', :notice, administrator_scheduled_assignment_submissions_path(@assignment_submission.scheduled_assignment))
    else
      render(:action => 'delete')
    end
  end

  protected

    def find_scheduled_assignment
      @scheduled_assignment = ScheduledAssignment.non_deleted.find(params[:scheduled_assignment_id])
    rescue ActiveRecord::RecordNotFound
      flash_and_redirect_to('The requested scheduled assignment does not exist', :error, administrator_root_path)
    end

    def find_assignment_submission
      @assignment_submission = AssignmentSubmission.non_deleted.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash_and_redirect_to('The requested assignment submission does not exist', :error, administrator_assignments_path)
    end

end

app/controllers/administrator/assignments_controller.rb
class Administrator::AssignmentsController < Administrator::BaseController

  before_filter :find_lesson, :only => [ :index, :new, :create ]
  before_filter :find_assignment, :except => [ :index, :new, :create ]

  def index
    @assignments = @lesson.assignments.paginate(:page => params[:page])
  end

  def show
  end

  def new
    @assignment = @lesson.assignments.build
  end

  def create
    @assignment = @lesson.assignments.build(params[:assignment])

    if @assignment.save
      flash_and_redirect_to('You have successfully created a new assignment', :notice, administrator_lesson_assignments_path(@lesson))
    else
      render(:action => 'new')
    end
  end

  def edit
  end

  def update
    if @assignment.update_attributes(params[:assignment])
      flash_and_redirect_to('The assignment has been updated successfully', :notice, administrator_lesson_assignments_path(@assignment.lesson))
    else
      render(:action => 'edit')
    end
  end

  def delete
  end

  def destroy
    if @assignment.delete!
      flash_and_redirect_to('Your assignment has been deleted successfully', :notice, administrator_lesson_assignments_path(@assignment.lesson))
    else
      render(:action => 'delete')
    end
  end

  protected

    def find_lesson
      @lesson = Lesson.non_deleted.find(params[:lesson_id])
    rescue ActiveRecord::RecordNotFound
      flash_and_redirect_to('The requested lesson does not exist', :error, administrator_lessons_path)
    end

    def find_assignment
      @assignment = Assignment.non_deleted.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash_and_redirect_to('The requested assignment does not exist', :error, administrator_lessons_path)
    end

end

app/controllers/administrator/attachments_controller.rb
class Administrator::AttachmentsController < Administrator::BaseController

  before_filter :find_attachable, :attachable_setup_page, :only => [ :index, :new, :create, :order, :change_image_order ]
  before_filter :find_attachment, :attachment_setup_page, :only => [ :show, :edit, :update, :delete, :destroy ]

  def order
    params[:attachment_thumbnails].each_with_index do |id, index|
      Attachment.update_all(['position = ?', index + 1], ['id = ?', id])
    end
    render :nothing => true
  end

  def index
    @attachments = @attachable.attachments.order(:position)

  end

  def show

  end

  def new
    @attachment = build_attachment
  end

  def create
  # abort(params[:attachment].to_a.to_s)
    @attachment = build_attachment(params[:attachment])
   # @attachment.vimeo_asset = '';
    if @attachment.save
      respond_to do |format|
        format.html { flash_and_redirect_to('Your attachment has been created successfully', :notice, polymorphic_attachments_path(@attachment.attachable)) }
        format.js { render :text => get_upload_text(@attachment) }
        format.json { render :json => basic_uploads_json(@attachment) }
      end
    else
      respond_to do |format|
        format.html { render(:action => 'new') }
        format.js { render :text => message }
        format.json { render :json => { :success => false, :message => message } }
      end
    end
  end

  def edit
    @attachable = @attachment.attachable
  end

  def update
    if @attachment.update_attributes(params[:attachment])
      flash_and_redirect_to('Your attachment has been updated successfully', :notice, polymorphic_attachments_path(@attachment.attachable))
    else
      render(:action => 'edit')
    end
  end

  def delete
    logger.debug('here')
    logger.debug(@attachment.to_yaml) if !@attachment.nil?
  end

  def destroy
    if @attachment.delete!
      flash_and_redirect_to('Your attachment has been deleted successfully', :notice, polymorphic_attachments_path(@attachment.attachable))
    else
      render(:action => 'delete')
    end
  end
  # Action for change current image order and update position of images
  def change_image_order
    params[:attachment_thumbnails].split(',').each_with_index do |id, index|
      Attachment.update_all(['position = ?', index + 1], ['id = ?', id])
    end
    respond_to do |format|
      format.js
    end
  end
protected

  def get_upload_text(attachment)
    raise 'implement get_upload_text in your controller'
  end

  def basic_uploads_json(attachment)
    attachment.to_json(:only => [:id, :file_name])
  end

  def attachable_setup_page
    page_config do |page|
      page.secondary_navigation_section = @attachable.class.name.pluralize.downcase.to_sym
      page.title.unshift("Attachments")
    end
  end

  def attachment_setup_page
    page_config do |page|
      page.secondary_navigation_section = @attachment.attachable.class.name.pluralize.downcase.to_sym
      page.title.unshift("Attachments")
    end
  end

end

app/controllers/administrator/base_controller.rb
class Administrator::BaseController < ApplicationController

  layout 'administrator'
  before_filter :require_administrator_user
  before_filter :setup_page

  protected

    def setup_page
      page_config do |page|
        page.body_tag_options[:class] = 'administrator'
        page.primary_navigation_section = :administrator_area
        page.secondary_navigation = true
        page.title.unshift('Administrator Area')
      end
    end

end

app/controllers/administrator/certificate_controller.rb
class Administrator::CertificateController < Administrator::BaseController
    
  def index   
  
  end
  
  def generate  
	@data = request.POST
	html = render_to_string(:action => :generate, :layout => "certificate.html") 
	pdf = WickedPdf.new.pdf_from_string(html) 
	send_data(pdf, :filename  => "certificate.pdf", :disposition => 'attachment') 
	
  end

  
  

end

app/views/administrator/testimonials/_new_and_edit_form.html.erb
<div class="grid_16 margin_top_20 alpha omega">
  <%= uni_form_for(@testimonial, :url => polymorphic_path([ :administrator, testimonial ]), :html => { :multipart => true }) do |f| %>
    <% f.fieldset(:type => "block", :legend => "Testimonial Details") do %>
      <%= f.text_field(:title, :size => '30', :label => "Title", :required => true, :style => "width: 99%;") %>
      <%= f.text_area(:content, :size => '60x3', :class => 'widgEditor', :label => "Content", :style => "width: 99%; height: 300px;") -%>
      <%= f.file_field :logo, :label => "Logo" %>
    <% end %>

    <div class="clear">&nbsp;</div><br />
    <p class="buttons"><%= pretty_button (testimonial.new_record? ? "Create" : "Update"), {:icon_path => "icons/tick.png"} %>
  <% end %>
</div>

app/views/administrator/testimonials/delete.html.erb
<div class="grid_16 margin_top_20 alpha omega">
  <h6>Delete Testimonial <%= h(@testimonial.title) -%></h6>
  <table class="pretty">
    <thead>
      <tr>
        <th class="centred">Title</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= h(@testimonial.title) %></td>
      </tr>
    </tbody>
  </table>

  <%= form_for([ :administrator, @testimonial ], :html => { :method => :delete }) do |f| %>
    <div class="clear">&nbsp;</div><br />
    <p class="buttons"><%= pretty_button "Delete", {:icon_path => "icons/delete.png"} %>
  <% end %>
</div>

app/views/administrator/testimonials/edit.html.erb
<h1>Editing Testimonial</h1>
<%= render(:partial => 'new_and_edit_form', :locals => { :testimonial => @testimonial }) -%>

app/views/administrator/testimonials/index.html.erb
<div class="grid_11 margin_top_20 alpha">
  <% unless @setting.blank? %>
    <table summary="List of courses" class="pretty">
      <thead>
        <tr>
          <th>Key</th>
          <th>Value</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @setting.key.try(:titleize) -%></td>
          <td><%= @setting.value -%></td>
          <td align="right">
            <%= link_to(image_tag("icons/pencil.png", :alt => "Edit Setting"), edit_administrator_setting_path(@setting), :rel => "Edit Setting", title: "Edit") -%>
            &nbsp;
        </tr>
      </tbody>
    </table>
  <% end %>
  <% unless @testimonials.blank? %>
    <table summary="List of testimonials" class="pretty">
      <thead>
        <tr>
          <th>Logo</th>
          <th>Title</th>
          <th>Content</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% @testimonials.each do |testimonial| %>
          <tr>
            <td valign="top" style="vertical-align: top;"><%= image_tag(testimonial.logo_url(:thumb), :alt => testimonial.title) if testimonial.logo? -%></td>

            <td valign="top" style="vertical-align: top;"><%= link_to(h(testimonial.title), edit_administrator_testimonial_path(testimonial), title: "Edit") -%></td>

            <td><%= testimonial.content.html_safe %></td>
                <td valign="top" style="vertical-align: top;" align="right">
                  <%= link_to(image_tag("icons/pencil.png", :alt => "Edit partner"), edit_administrator_testimonial_path(testimonial), :rel => "Edit Testimonial", title: "Edit") -%>
                  &nbsp;
                  <%= link_to(image_tag("icons/delete.png", :alt => "Delete Testimonial"), delete_administrator_testimonial_path(testimonial), :rel => "Delete this Testimonial", title: "Delete") -%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%#= will_paginate(@testimonials) %>
  <% else %>
    <p>No testimonials exist.</p>
  <% end %>
</div>
<div class="grid_5 margin_top_20 omega">
  <p class="buttons">
    <%= pretty_button_link "Create new testimonial", new_administrator_testimonial_path, {:icon_path => "icons/add.png"} %>
  </p>
</div>
<div class="clear">&nbsp;</div>

app/views/administrator/testimonials/new.html.erb
<h1>New Testimonial</h1>

<%= render(:partial => 'new_and_edit_form', :locals => { :testimonial => @testimonial }) -%>

app/views/administrator/testimonials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @administrator_testimonial.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @administrator_testimonial.content %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @administrator_testimonial.logo %>
</p>

<%= link_to 'Edit', edit_administrator_testimonial_path(@administrator_testimonial) %> |
<%= link_to 'Back', administrator_testimonials_path %>