config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', :constraints => lambda { |request|
    User.find_by(id: request.session[:user_id]).try(:administrator?)
  }

  namespace :administrator do
    get 'contest_descriptions/new'
  end

  namespace :administrator do
    get 'contest_descriptions/index'
  end

  namespace :administrator do
    get 'contest_descriptions/create'
  end

  namespace :administrator do
    resources :testimonials do
      member do
        get 'delete'
      end
    end
    resource :special
    resources :reports, only: [:new, :create]
    resources :users do
      member do
        get 'delete'
      end
      collection do
        get 'export'
      end
      resource :activation, :only => :create
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
    end
    get :change_image_order, to: 'attachments#change_image_order'

    resources :attachments, :except => [:index, :new, :create] do
      member do
        get 'delete'
      end
      resources :critiques, :only => [:new, :create]
    end

    resources :courses do
      member do
        get 'delete'
      end

      resources :attachments, :only => [:index, :new, :create]
      resources :forum_topics, :only => [:index, :new, :create]
      resources :lessons, :only => [:index, :new, :create]
      #resources :scheduled_courses, :only => [:index, :new,:create]
      resources :scheduled_courses, only: [:index]
    end

    resources :blogs do
      member do
        get 'delete'
      end

      resources :attachments, :only => [:index, :new, :create]
    end

    resources :certificate, only: [:index, :generate] do
      collection do
        post 'generate'
      end
    end
    resources :renewals, only: [:index, :create, :destroy]

    resources :workshops do
      member do
        get 'delete'
      end
    end

    resources :packages do
      member do
        get 'delete'
      end
      resources :attachments, :only => [:index, :new, :create]
    end

    resources :banner_images, only: [:index, :create, :destroy]
    resources :student_galleries, only: [:index, :create, :destroy]
    resources :contests, only: [:index, :create, :destroy, :new]
    resources :contest_descriptions, only: [:index, :create, :new, :edit]

    resources :settings

    resources :forum_topics do
      member do
        get 'delete'
      end
      resources :posts, :controller => 'forum_posts', :only => [:new, :create]
    end

    resources :lessons, :except => [:index, :new, :create] do
      member do
        get 'delete'
      end
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
      resources :assignments, :only => [:index, :new, :create]
    end

    resources :assignments, :except => [:index, :new, :create] do
      member do
        get 'delete'
      end
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
      resources :rearrangements
    end

    resources :rearrangements, :except => [:index, :new, :create] do
      member do
        get 'delete'
      end
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
    end

    resources :scheduled_assignments, :only => :show do
      resources :submissions, :controller => 'assignment_submissions', :only => :index
    end

    resources :assignment_submissions, :except => [:index, :new, :create] do
      member do
        get 'delete'
      end
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
      resources :critiques, :only => [:new, :create]
    end

    resources :scheduled_courses, :only => [:show] do
      resources :enrolments, :only => [:index, :new, :create]
    end

    resources :critiques, :only => [:edit, :update, :destroy] do
      member do
        get 'delete'
      end
    end

    resources :enrolments, :only => [:edit, :update, :destroy] do
      member do
        get 'delete'
      end
    end

    resources :forum_posts, :only => [:edit, :update, :destroy] do
      member do
        get 'delete'
      end
    end

    resources :exchange_rates, :except => :show do
      member do
        get 'delete'
      end
    end

    resources :partners do
      member do
        get 'delete'
      end
    end

    resources :gifts
  end

  namespace :instructor do
    resource :account, :controller => 'users', :only => [:edit, :update]
    resources :attachments do
      member do
        get 'delete'
      end
    end

    resources :lessons_comment, :only => [:delete] do
      member do
        get 'delete'
      end
    end
    resources :lessons, :only => :show
    resources :assignments, :only => :show
    resources :updates, :only => [:index]
    resources :mystudents, :only => [:index] do
      member do
        get 'courses'
      end
    end
    resources :courses, :only => :index do
      resources :scheduled_courses, :only => :index
    end
    resources :scheduled_courses, :only => [:show, :destroy] do
      member do
        get 'delete'
      end
      resources :enrolments, :only => [:index, :new, :create]
    end
    resources :forum_topics, :except => :destroy do
      resources :posts, :controller => 'forum_posts', :only => [:new, :create]
    end

    resources :submissions, :controller => 'assignments_submissions', :except => [:new, :create] do
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
        end
      end
      resources :critiques, :controller => 'assignment_critiques', :only => [:new, :create]
      #resource :sequence
    end
    resources :forum_posts, :only => [:edit, :update]
    get 'sequence/:id', :controller => "assignment_submissions", :action => 'sequence', as: :instructor_sequence

    get 'lessons/:lesson_id/attachments/new', :controller => "upload_video", :action => 'new', :as => 'lession'
    get 'lessons/:lesson_id/attachments', :controller => "upload_video", :action => 'new', :as => 'lession1'
    post 'lessons/:lesson_id/attachments', :controller => "upload_video", :action => 'create', :as => 'path_video'
    #
    get 'lessons/:lesson_id/upload', :controller => "upload_video", :action => 'upload', :as => 'inst_assignment'
    get 'lessons/:lesson_id', :controller => "upload_video", :action => 'upload', :as => 'inst_assignment1'
    post 'lessons/:lesson_id', :controller => "upload_video", :action => 'upload_video', :as => 'path_video_attach'
  end
  get 'courses/fulldownload', :controller => 'courses', :action => 'fulldownload'

  namespace :student do
    resource :account, :controller => 'users', :only => [:edit, :update]
    resources :attachments do
      member do
        get 'delete'
      end
      collection do
        post 'order'
      end
    end

    resources :courses, :controller => 'scheduled_courses' do
      resources :lessons, :controller => 'scheduled_lessons', :only => :show
      resources :reviews, only: [:new, :create, :destroy]
    end

    resources :assignments, :controller => 'scheduled_assignments' do
      resources :submissions, :controller => 'assignment_submissions', :only => [:new, :create]
    end

    resources :submissions, :controller => 'assignment_submissions', :except => [:new, :create] do
      resources :attachments, :only => [:index, :new, :create] do
        collection do
          post 'order'
          get 'sequence'
        end
      end
      resources :critiques do
        resources :critiques, :only => [:new, :create]
      end
    end

    resources :forum_topics, :except => :destroy do
      resources :posts, :controller => 'forum_posts', :only => [:new, :create]
    end
    resources :updates, :only => [:index]
    resources :forum_posts, :only => [:edit, :update]

    get 'sequence/:id', :controller => "assignment_submissions", :action => 'sequence', as: :student_sequence

    get 'lessons/:lesson_id/assignments/:assignments_id/attachments/new', :controller => "upload_video", :action => 'new', :as => 'stdunt_post_video'
    get 'lessons/:lesson_id/assignments/:assignments_id/attachments', :controller => "upload_video", :action => 'new', :as => 'stdunt_post_video1'
    post 'lessons/:lesson_id/assignments/:assignments_id/attachments', :controller => "upload_video", :action => 'create', :as => 'post_video'
  end
  get 'attachments/:id/:style.:format', :controller => 'attachments', :action => 'download', as: :attachment_download

  get "paypal" => "purchase_notifications#paypal", :path => "purchase_notifications/paypal"

  post 'purchase_notifications/:gateway', :controller => 'purchase_notifications', :action => 'create', :requirements => {:gateway => /[a-z_]+/i}, as: :purchase_notifications

  post 'package_purchase_notifications/:gateway', :controller => 'package_purchase_notifications', :action => 'create', :requirements => {:gateway => /[a-z_]+/i}, as: :package_purchase_notifications

  get 'purchase_complete/:gateway', :controller => 'purchase_completions', :action => 'create', :requirements => {:gateway => /[a-z_]+/i}, as: :purchase_completions

  resources :instructors, :only => [:index, :show]

  resources :courses, :only => [:index, :show] do
    resource :purchase, :only => [:new, :create] do
      get 'renew' => 'purchases#renew'
      post 'renew_subscription' => 'purchases#renew_subscription'
    end
  end
  resources :gifts

  put '/courses/:course_id/enrolments/:id/unsubscribe', to: 'purchases#unsubscribe', as: :unsubscribe_course
  get '/courses/:course_id/purchases/:id/execute', to: 'purchases#execute', as: :payment_execute
  get '/gifts/:gift_id/execute', to: 'gifts#execute', as: :gift_execute

app/controllers/administrator/attachments_controller.rb
class Administrator::AttachmentsController < Administrator::BaseController

  before_filter :find_attachable, :attachable_setup_page, :only => [ :index, :new, :create, :order, :change_image_order ]
  before_filter :find_attachment, :attachment_setup_page, :only => [ :show, :edit, :update, :delete, :destroy ]

  def order
    params[:attachment_thumbnails].each_with_index do |id, index|
      Attachment.update_all(['position = ?', index + 1], ['id = ?', id])
    end
    render :nothing => true
  end

  def index
    @attachments = @attachable.attachments.order(:position)

  end

  def show

  end

  def new
    @attachment = build_attachment
  end

  def create
  # abort(params[:attachment].to_a.to_s)
    @attachment = build_attachment(params[:attachment])
   # @attachment.vimeo_asset = '';
    if @attachment.save
      respond_to do |format|
        format.html { flash_and_redirect_to('Your attachment has been created successfully', :notice, polymorphic_attachments_path(@attachment.attachable)) }
        format.js { render :text => get_upload_text(@attachment) }
        format.json { render :json => basic_uploads_json(@attachment) }
      end
    else
      respond_to do |format|
        format.html { render(:action => 'new') }
        format.js { render :text => message }
        format.json { render :json => { :success => false, :message => message } }
      end
    end
  end

  def edit
    @attachable = @attachment.attachable
  end

  def update
    if @attachment.update_attributes(params[:attachment])
      flash_and_redirect_to('Your attachment has been updated successfully', :notice, polymorphic_attachments_path(@attachment.attachable))
    else
      render(:action => 'edit')
    end
  end

  def delete
    logger.debug('here')
    logger.debug(@attachment.to_yaml) if !@attachment.nil?
  end

  def destroy
    if @attachment.delete!
      flash_and_redirect_to('Your attachment has been deleted successfully', :notice, polymorphic_attachments_path(@attachment.attachable))
    else
      render(:action => 'delete')
    end
  end
  # Action for change current image order and update position of images
  def change_image_order
    params[:attachment_thumbnails].split(',').each_with_index do |id, index|
      Attachment.update_all(['position = ?', index + 1], ['id = ?', id])
    end
    respond_to do |format|
      format.js
    end
  end
protected

  def get_upload_text(attachment)
    raise 'implement get_upload_text in your controller'
  end

  def basic_uploads_json(attachment)
    attachment.to_json(:only => [:id, :file_name])
  end

  def attachable_setup_page
    page_config do |page|
      page.secondary_navigation_section = @attachable.class.name.pluralize.downcase.to_sym
      page.title.unshift("Attachments")
    end
  end

  def attachment_setup_page
    page_config do |page|
      page.secondary_navigation_section = @attachment.attachable.class.name.pluralize.downcase.to_sym
      page.title.unshift("Attachments")
    end
  end

end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController

  def download
    head(:not_found) and return if (attachment = Attachment.find_by_id(params[:id])).nil?

    style = params[:style] || :original
    
    redirect_to(attachment.s3_url(style))
  end

end

app/controllers/instructor/attachments_controller.rb
class Instructor::AttachmentsController < Instructor::BaseController

  before_filter :find_attachable, :only => [ :new, :create ]
  before_filter :find_attachment, :only => [ :show, :edit, :update, :delete, :destroy ]

  def order
    @assignment_submission = AssignmentSubmission.find(params[:submission_id])
    @assignment_submission.rearrangement = params[:attachment_thumbnails]
    @assignment_submission.save!
  end

  def index
    @attachments = AssignmentSubmission.find(params[:submission_id])
  end

  def show
  end

  def new
    @attachment = build_attachment
  end

  def create
    @attachment = build_attachment(params[:attachment])

    if @attachment.save
      flash_and_redirect_to('Your attachment has been created successfully', :notice, polymorphic_attachments_path(@attachment.attachable))
    else
      render(:action => 'new')
    end
  end

  def edit
  end

  def update
    if @attachment.update_attributes(params[:attachment])
      submission = AssignmentSubmission.find(params[:submission_id])
      flash_and_redirect_to('Your attachment has been updated successfully', :notice, instructor_submission_path(submission))
    else
      render(:action => 'edit')
    end
  end

  def delete
  end

  def destroy
    if @attachment.delete
      submission = AssignmentSubmission.find(params[:submission_id])
      flash_and_redirect_to('Your attachment has been deleted successfully', :notice, instructor_submission_path(submission))
    else
      render(:action => 'delete')
    end
  end
end

app/controllers/student/base_controller.rb
class Student::BaseController < ApplicationController

  layout 'student'
  before_filter :require_student_user
  before_filter :setup_page
  
protected

  def setup_page
    page_config do |page|
      page.body_tag_options[:class] = 'student'
      page.primary_navigation_section = :student_area
      page.secondary_navigation = true
      page.title.unshift('Student Area')
    end
  end

end

app/controllers/student/critiques_controller.rb
class Student::CritiquesController < Student::BaseController
  
  def new
    @assignment_submission = AssignmentSubmission.find_by_id(params[:submission_id])
    @critique = Critique.find_by_id(params[:critique_id])
    redirect_to(student_root_path) if @assignment_submission.nil? || @critique.nil?
  end
  
  def create
    @assignment_submission = AssignmentSubmission.find_by_id(params[:submission_id])
    if params[:critique][:comment].blank?
      redirect_to(student_submission_path(@assignment_submission))
    else
      @critique = Critique.find_by_id(params[:critique_id])
      @new_critique = @critique.critiqueable.critiques.build(params)
      @new_critique.user = current_user
      @new_critique.critiqueable = @critique.critiqueable
      @new_critique.comment = params[:critique][:comment]
      @new_critique.save!
      redirect_to(student_submission_path(@assignment_submission))
    end
  end

end

app/controllers/student/forum_posts_controller.rb
class Student::ForumPostsController < Student::BaseController

  include Theia::ActsAsDiscussable::Controller

  before_filter :find_forum_topic, :only => [ :new, :create ]
  before_filter :find_forum_post, :require_edit_permission, :only => [ :edit, :update ]

  def new
    @forum_post = build_forum_post
  end

  def create
    redirect = (params[:forum_post].has_key?(:redirect) ? params[:forum_post][:redirect] : nil) if params.has_key?(:forum_post)
    @forum_post = build_forum_post(params[:forum_post])

    if @forum_post.save
      @forum_post.attachments << Attachment.create(asset: params[:forum_post][:file], owner_user_id: current_user.id)
      flash_and_redirect_to('Your forum post has been created successfully', :notice, redirect.nil? ? student_forum_topic_path(@forum_post.topic) : redirect)
    else
      render(:action => 'new')
    end
  end

  def edit
  end

  def update
    if @forum_post.update_attributes(params[:forum_post])
      flash_and_redirect_to('Your forum post has been updated successfully', :notice, student_forum_topic_path(@forum_post.topic))
    else
      render(:action => 'edit')
    end
  end

  protected

    def require_edit_permission
      flash_and_redirect_to('You are not allowed to edit the post', :error, student_forum_topic_path(@forum_post.topic)) unless @forum_post.editable?(current_user)
    end

end

app/views/student/attachments/_attachments.html.erb
<% if attachments.size > 0 %>
  <div class="callout_box<%= " #{classes}" if local_assigns[:classes] -%>" style="min-height: 100px;">
    <h4><%= title if local_assigns[:classes] -%></h4>
    <div class="body padding_5 attachments">
      <%- attachments.each_with_index do |attachment, index| %>
        <p>
          <%- if attachment.image? || attachment.video? -%>
            <span><%= attachment_thumbnail(attachment, :style => :w60xh60, :lightview => true, :id => "sample#{index + 1}", size: '60x60') -%></span>
          <%- end -%>
        </p>
      <%- end %>
    </div>
  </div>
<% end %>

app/views/student/attachments/delete.html.erb
<%= render(:partial => 'attachments/delete_form', :locals => { :attachment => @attachment, :destroy_path => student_attachment_path(@attachment), :redirect => @redirect.nil? ? local_assigns[:redirect] ? redirect : nil : @redirect }) -%>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script>jQuery.noConflict();</script>
<script>
	jQuery(function($){	
		$(".lightview").each(function( i,j ) {
			str = $(this).attr('href');
			if (str.toLowerCase().indexOf("https://player.vimeo.com") >= 0){
				var filename = $(this).find('img').attr('src').replace( /^.*?([^\/]+)\..+?$/, '$1' );
				$(this).find('img').attr('src','/images/'+filename+'.png');
			}
		});
	})
</script>

app/views/student/attachments/edit.html.erb
<%= render(:partial => 'attachments/new_and_edit_form', :locals => { :attachment => @attachment, :path => student_attachment_path(@attachment), :redirect => @redirect.nil? ? local_assigns[:redirect] ? redirect : nil : @redirect }) -%>

app/views/student/attachments/index.ajax.erb
<ol id="attachment_thumbnails">
  <% @attachments.each do |attachment| %>
    <li id="attachment_thumbnail_li_<%= attachment.id -%>"><div class="photo_frame_header">&nbsp;</div><div class="photo_frame"><%= image_tag(attachment.s3_url(:w60xh60), :alt => attachment.title, :title => attachment.title, :class => "draggable", :id => "attachment_thumbnail_#{attachment.id}") -%><div class="controls"><%= link_to(image_tag("icons/magnifier.png"), get_attachment_url(attachment, style: 'detail'), :class => "lightview") -%><%= link_to(image_tag("icons/pencil.png"), edit_student_attachment_path(attachment)) -%><%= link_to(image_tag("icons/delete.png"), delete_student_attachment_path(attachment)) -%></div></div><div class="photo_frame_footer">&nbsp;</div></li>
  <% end %>
</ol>

app/views/student/attachments/index.html.erb
<div class="grid_11 margin_top_20 alpha">
  <h4>My Photos &amp; Videos</h4>
  <% if @attachments.empty? %>
    <p class="margin_bottom_20">You have no images or videos in your personal gallery. To get started, upload pictures or video to your personal gallery now!</p>
  <% else %>
    <p>You currently have <%= pluralize(@attachments.size, "item") -%> in your gallery. You can upload pictures or video to your personal gallery at any time.</p>
  <% end %>
  <h5>Upload Files</h5>
  <div id="degraded_container">
    <p><%= link_to('Create new attachment', polymorphic_attachments_path(@attachable, :singular => true, :action => :new)) -%></p>
    <p>You may also wish to ensure Javascript is enabled and Flash installed for a better upload experience.</p>
  </div>
  <div id="swfupload_container">
    <form>
      <div id="swf_upload_UI">
        <p><span id="swf_button_holder"></span></p>
        <div id="swf_fs_upload_progress">
          <span class="legend"></span>
          <p id="divStatus"></p>
        </div>
      </div>
    	<noscript class="swf-error-msg"><p><%= link_to('Create new attachment', polymorphic_attachments_path(@attachable, :singular => true, :action => :new)) -%></p></noscript>
    	<div id="swf_loading_content" class="swf-error-msg" style="display:none;"><%= t('uploader.swf_loading') %></div>
    	<div id="swf_long_loading" class="swf-error-msg" style="display:none;"><%= t('uploader.swf_taking_to_long') %></div>
    	<div id="swf_alternate_content" class="swf-error-msg" style="display: none;"><%= t('uploader.swf_not_loading', :url => '<a href="http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash">Adobe Website</a>') %></div>
  	</form>
  </div>

  <%= render :partial => 'attachments/flash_upload_javascript', :locals => { :path => polymorphic_attachments_path(@attachable), :ajax_path => polymorphic_attachments_path(@attachable, :format => 'ajax') } %>
  <div id="attachment_thumbnail_container">
    <h5>Gallery</h5>
    <% unless @attachments.empty? %>
      <ol id="attachment_thumbnails">
        <% @attachments.each do |attachment| %>
          <li id="attachment_thumbnail_li_<%= attachment.id -%>"><div class="photo_frame_header">&nbsp;</div><div class="photo_frame"><%= image_tag(attachment.s3_url(:w60xh60), :alt => attachment.title, :title => attachment.title, :class => "draggable", :id => "attachment_thumbnail_#{attachment.id}") -%><div class="controls"><%= link_to(image_tag("icons/magnifier.png"), get_attachment_url(attachment, style: 'detail'), :class => "lightview") -%><%= link_to(image_tag("icons/pencil.png"), edit_student_attachment_path(attachment)) -%><%= link_to(image_tag("icons/delete.png"), delete_student_attachment_path(attachment)) -%></div></div><div class="photo_frame_footer">&nbsp;</div></li>
        <% end %>
      </ol>
    <% end %>
  </div>
  <%#= sortable_element("attachment_thumbnails", :url => { :action => "order" }, :handle => "draggable", :constraint => "horizontal", :overlap => "horizontal") -%>
</div>
<div class="grid_5 margin_top_20 omega">
  <%= render(:partial => "student/forum_topics/latest", :locals => {:classes => "margin_bottom_20"}) -%>
  <%= render(:partial => "student/forum_topics/latest_from_courses", :locals => {:classes => "margin_bottom_20"}) -%>
</div>
<div class="clear">&nbsp;</div>

app/views/student/attachments/new.html.erb
<%= render(:partial => 'attachments/new_and_edit_form', :locals => { :attachment => @attachment, :path => polymorphic_attachments_path(@attachment.attachable), :redirect => @redirect.nil? ? local_assigns[:redirect] ? redirect : nil : @redirect }) -%>

app/views/student/attachments/order.js.erb
$('.show_flash').replaceWith('<%= content_tag "p", "image order sucessfully updated", :class => "flash notice"%>');

app/views/student/attachments/sequence.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'image_ordering'%>
<% end %>
<div class="grid_11 margin_top_20 alpha">
  <div id="attachment_thumbnail_container">
    <p>Drag and drop the images then click on ' Save Position ' button to rearrange the sequence</p>
    <% unless @attachments.empty? %>
      <ol id="attachment_thumbnails">
        <% @attachments.each do |attachment| %>
          <li id="attachment_thumbnail_li_<%= attachment.id -%>"><div class="photo_frame_header">&nbsp;</div><div class="photo_frame"><%= image_tag(attachment.s3_url(:w60xh60), :alt => attachment.title, :title => attachment.title, :class => "draggable", :id => "attachment_thumbnail_#{attachment.id}") -%><div class="controls"><%= link_to(image_tag("icons/magnifier.png"), get_attachment_url(attachment, style: 'detail'), :class => "lightview") -%><%= link_to(image_tag("icons/pencil.png"), edit_student_attachment_path(attachment, :redirect => sequence_student_submission_attachments_path(@attachable))) -%><%= link_to(image_tag("icons/delete.png"), delete_student_attachment_path(attachment, :redirect => sequence_student_submission_attachments_path(@attachable))) -%></div></div><div class="photo_frame_footer">&nbsp;</div></li>
        <% end %>
      </ol>
    <% end %>
  </div>
  <%# sortable_element_js("attachment_thumbnails", :url => { :action => "order" }, :handle => "draggable", :constraint => "horizontal", :overlap => "horizontal") -%>
</div>

<div class="grid_5 margin_top_20 omega">
  <%= link_to("Back to assignment", student_submission_path(@attachable)) -%>
</div>
<div class="grid_5 margin_top_20 omega">
  <% unless @attachments.blank?%>
      <%= form_tag order_student_attachments_path, method: :post, remote: true do %>
        <%= hidden_field_tag :attachment_thumbnails %>
        <%= submit_tag 'save position' %>
      <% end %>
  <% end %>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script>jQuery.noConflict();</script>
<script>
	jQuery(function($){	
		$(".photo_frame").each(function( i,j ) {
			str = $(this).find('.lightview').attr('href');
			if (str.toLowerCase().indexOf("https://player.vimeo.com") >= 0){
				var filename = $(this).find('img:first').attr('src').replace( /^.*?([^\/]+)\..+?$/, '$1' );
				$(this).find('img:first').attr('src','/images/'+filename+'.png');
			}
		});
	})
</script>

app/views/student/attachments/show.html.erb
<%- if @attachment.image? -%>
  <%= image_tag(@attachment.s3_url(:detail), :alt => 'Attachment', :title => @attachment.title) %>
<%- else -%>
  <p><%= link_to('Download', @attachment.s3_url(:original)) -%></p>
<%- end -%>
<dl>
  <dt>Title</dt>
  <dd><%= h(@attachment.title) %></dd>
  <dt>Given name</dt>
  <dd><%= h(@attachment.description) %></dd>
</dl>
<p><%= link_to('Edit this attachment', edit_student_attachment_path(@attachment)) %></p>
<p><%= link_to('Delete this attachment', delete_student_attachment_path(@attachment)) %></p>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script>jQuery.noConflict();</script>
<script>
	jQuery(function($){	
		$(".lightview").each(function( i,j ) {
			str = $(this).attr('href');
			if (str.toLowerCase().indexOf("https://player.vimeo.com") >= 0){
				var filename = $(this).find('img').attr('src').replace( /^.*?([^\/]+)\..+?$/, '$1' );
				$(this).find('img').attr('src','/images/'+filename+'.png');
			}
		});
	})
</script>